# Generated by Django 5.2.5 on 2025-09-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_loign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
